-- Criação das Tabelas DEPARTAMENTO_01 e FUNCIONARIO_02
CREATE TABLE DEPARTAMENTO_01 (
    A01_CODIGO NUMBER(5) NOT NULL PRIMARY KEY,
    A01_NOME VARCHAR2(40) NOT NULL,
    A01_LOCAL VARCHAR2(40) NOT NULL
);
 
CREATE TABLE FUNCIONARIO_02 (
    A02_CODIGO NUMBER(5) NOT NULL PRIMARY KEY,
    A02_NOME VARCHAR2(40) NOT NULL,
    A02_CARGO VARCHAR2(40) NOT NULL,
    A02_SALARIO NUMBER(10,2) NOT NULL,
    A01_CODIGO NUMBER(5) NOT NULL,
    CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO FOREIGN KEY (A01_CODIGO) REFERENCES DEPARTAMENTO_01(A01_CODIGO)
);