-- Procedures de Inserção de informaçoes com AUTO INCREMENT
--Procedure de inserção para DEPARTAMENTO_01
CREATE OR REPLACE PROCEDURE PROC_INS_DEPARTAMENTO_01 (
    V_A01_NOME IN DEPARTAMENTO_01.A01_NOME%TYPE,
    V_A01_LOCAL IN DEPARTAMENTO_01.A01_LOCAL%TYPE
)
IS
    V_A01_CODIGO DEPARTAMENTO_01.A01_CODIGO%TYPE;
BEGIN
    SELECT MAX(A01_CODIGO)
    INTO V_A01_CODIGO 
    FROM DEPARTAMENTO_01;

    IF V_A01_CODIGO IS NULL THEN
        V_A01_CODIGO := 1;
    ELSE
        V_A01_CODIGO := V_A01_CODIGO + 1;
    END IF;

    INSERT INTO DEPARTAMENTO_01 (A01_CODIGO, A01_NOME, A01_LOCAL)
    VALUES (V_A01_CODIGO, V_A01_NOME, V_A01_LOCAL);

    COMMIT;
END;

--Bloco anonimo PROC_INS_DEPARTAMENTO_01
BEGIN
    PROC_INS_DEPARTAMENTO_01('Presidência', '20º andar');
    PROC_INS_DEPARTAMENTO_01('Diretoria', '18° andar');
    PROC_INS_DEPARTAMENTO_01('Vendas', 'Térreo');
    PROC_INS_DEPARTAMENTO_01('TI', 'Sub-solo');
END;


--Procedure de inserção para FUNCIONARIO_02
CREATE OR REPLACE PROCEDURE PROC_INS_FUNCIONARIO_02 (
    V_A02_NOME IN FUNCIONARIO_02.A02_NOME%TYPE,
    V_A02_CARGO IN FUNCIONARIO_02.A02_CARGO%TYPE,
    V_A02_SALARIO IN FUNCIONARIO_02.A02_SALARIO%TYPE,
    V_A01_CODIGO IN FUNCIONARIO_02.A01_CODIGO%TYPE
)
IS
    V_A02_CODIGO FUNCIONARIO_02.A02_CODIGO%TYPE;
BEGIN
    SELECT MAX(A02_CODIGO)
    INTO V_A02_CODIGO 
    FROM FUNCIONARIO_02;

    IF V_A02_CODIGO IS NULL THEN
        V_A02_CODIGO := 1;
    ELSE
        V_A02_CODIGO := V_A02_CODIGO + 1;
    END IF;

    INSERT INTO FUNCIONARIO_02(A02_CODIGO, A02_NOME, A02_CARGO, A02_SALARIO, A01_CODIGO)
    VALUES (V_A02_CODIGO, V_A02_NOME, V_A02_CARGO, V_A02_SALARIO, V_A01_CODIGO);

    COMMIT;
END;

--Bloco anonimo PROC_INS_FUNCIONARIO_02
BEGIN
    PROC_INS_FUNCIONARIO_02('Ruth Carvalho', 'Analista de TI', 4200.00, 4);
    PROC_INS_FUNCIONARIO_02('Asaph Carvalho', 'Diretor comercial', 6100.00, 2);
    PROC_INS_FUNCIONARIO_02('Daphne Mendes', 'CEO', 21000.00, 1);
    PROC_INS_FUNCIONARIO_02('Leonardo da Silva', 'Vendedor', 3300.00, 3);
END;